In [1]:
%load_ext autoreload
%autoreload 2
# import sys
# sys.path.append('/Users/jijy/PycharmProjects/')

In [2]:
from bailarn.ner import NamedEntityRecognizer,constant
from bailarn.utils import utils
import deepcut
import numpy as np

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead


# Read Text File

In [3]:
texts = utils.TextCollection(corpus_directory="./bailarn/data/BEST_mock", word_delimiter="|",tag_delimiter="/")
print("Corpus size : {}\n".format(texts.count))
print("Example corpus text : {}\n".format(texts.get_content(0)))

100%|██████████| 2/2 [00:00<00:00,  9.50it/s]


Finish
Corpus size : 2

Example corpus text : เฒ่า/NN/O|วัย/NN/O|72/CD/MEA_B|ร้อง/VV/O|ถูก/AUX/O|รัฐ/NN/O|ยึด/VV/O|ที่/NN/O|ทำกิน/JJV/O|ที่/COMP/O|มี/VV/O|สค./NR/ABB_B|1/OD/O|-/PU/O|เป็น/VV/O|พื้นที่/NN/O|สาธารณะ/NN/O||1/OD/DTM_B| |กันยายน/NN/DTM_I| |2550/OD/DTM_I|10:42/OD/DTM_B|น./CL/DTM_I||พ่อ/NN/O|เฒ่า/NN/O|วัย/NN/O|72/CD/MEA_B|ร้องขอ/VV/O|ความ/FXN/O|เป็นธรรม/VA/O|ถูก/AUX/O|เจ้าหน้าที่/NN/O|รัฐ/NN/O|ยึด/VV/O|ที่ดิน/NN/O|ทำกิน/JJV/O|ที่/COMP/O|มี/VV/O|เอกสาร/NN/O|ส.ค./NN/TRM_B|1/OD/TRM_I| |และ/CNJ/O|เป็น/VV/O|ที่ดิน/NN/O|มรดก/NN/O|กว่า/ADV/O|80/CD/MEA_B|ไร่/CL/MEA_I|เผย/VV/O|ทำกิน/VV/O|มา/VV/O|ตั้งแต่/P/O|รุ่น/NN/O|พ่อ/NN/O||ชี้/VV/O|รัฐ/NN/O|รังแก/VV/O|ประชาชน/NN/O|เตรียม/VV/O|เดินหน้า/VV/O|ยื่น/VV/O|หนังสือ/NN/O|นายก/NN/O|ฯ/PU/O| ||หาก/CNJ/O|ช่วย/VV/O|ไม่/NEG/O|ได้/AUX/O|จะ/AUX/O|ทำ/VV/O|ฎีกา/NN/O|ถวาย/VV/O|ในหลวง/NN/O||นายอำเภอ/NN/O|ฯ/PU/O|โต้/VV/O|จนท./NN/ABB_B|ทำ/VV/O|ถูกต้อง/ADV/O|ตาม/VV/O|กฎหมาย/NN/O|อ้าง/VV/O|ที่ดิน/NN/O|เป็น/VV/O|สมบัติ/NN/O|หลวง/JJA/O||(/PU/O|1/OD/DTM_B| |ก

In [86]:
# texts = utils.TextCollection(corpus_directory="./bailarn/categorization/data/corpus", tokenize_function=deepcut.deepcut.tokenize)

# Create Word Indexer from vocabs

In [4]:
# vocabs = []
# for corpus_idx in range(texts.count):
#     temp=[]
#     for word in texts.get_token_list(corpus_idx):
#         vocabs.append(word[0])
# #     vocabs.append(temp)

In [5]:
# vocabs = np.unique(["ไก่","ชอบ"," กิน","หยวก"]).tolist()
# vocabs = np.unique(vocabs).tolist()
# word_index = utils.index_builder(vocabs, start_index=1, reverse=False)
# word_index_r = utils.index_builder(vocabs, start_index=1, reverse=True)
# word_index_r[0] = '<PAD>'
# word_index['<PAD>'] = 0
# last_idx = len(word_index)
# word_index_r[last_idx] = 'UNK'
# word_index['UNK'] = last_idx
# word_index

In [7]:
# word2vec = Word_Embedder()
word_index = utils.build_word_index(texts)

Load words from text collection


100%|██████████| 2/2 [00:00<00:00, 969.45it/s]


Finish


In [6]:
sorted(word_index.items(), key=lambda x:x[1], reverse=False)[-10:]

[('แบ่ง', 463),
 ('35', 464),
 ('ถ่าย', 465),
 ('ด้วย', 466),
 ('พัฒนา', 467),
 ('พร้อม', 468),
 ('ไหน', 469),
 ('เสนอ', 470),
 ('ติดชัยภูมิ', 471),
 ('UNK', 472)]

In [17]:
tag_index = utils.build_tag_index(constant.TAG_LIST, start_index=0)
tag_index

{'ABB': 33,
 'ABB_B': 31,
 'ABB_DES_B': 25,
 'ABB_DES_I': 26,
 'ABB_I': 32,
 'ABB_LOC_B': 23,
 'ABB_LOC_I': 24,
 'ABB_ORG_B': 21,
 'ABB_ORG_I': 22,
 'ABB_PER_B': 27,
 'ABB_PER_I': 28,
 'ABB_TTL_B': 29,
 'ABB_TTL_I': 30,
 'BRN_B': 7,
 'BRN_I': 8,
 'DDEM': 34,
 'DES_B': 3,
 'DES_I': 4,
 'DTM_B': 1,
 'DTM_I': 2,
 'LOC_B': 15,
 'LOC_I': 16,
 'MEA_B': 11,
 'MEA_I': 12,
 'NAME_B': 35,
 'NUM_B': 13,
 'NUM_I': 14,
 'O': 37,
 'ORG_B': 19,
 'ORG_I': 20,
 'PER_B': 9,
 'PER_I': 10,
 'TRM_B': 17,
 'TRM_I': 18,
 'TTL_B': 5,
 'TTL_I': 6,
 'UNK': 38,
 'X': 0,
 '__': 36}

# Transform text into input

In [18]:
vs = utils.build_input(text_collection=texts, 
                       word_index=word_index, 
                       tag_index=tag_index, 
                       sequence_length=constant.SEQUENCE_LENGTH, 
                       target="ner", 
                       for_train=True)

Start building input...
Start generating x y...


100%|██████████| 2/2 [00:00<00:00, 602.76it/s]


In [19]:
vs.x

array([[ 69, 233, 363, ...,   0,   0,   0],
       [397, 411,  46, ...,   0,   0,   0]])

In [20]:
word_index['เฒ่า']

69

In [21]:
vs.readable_x

[['เฒ่า',
  'วัย',
  '72',
  'ร้อง',
  'ถูก',
  'รัฐ',
  'ยึด',
  'ที่',
  'ทำกิน',
  'ที่',
  'มี',
  'สค.',
  '1',
  '-',
  'เป็น',
  'พื้นที่',
  'สาธารณะ',
  '1',
  'กันยายน',
  '2550',
  '10:42',
  'น.',
  'พ่อ',
  'เฒ่า',
  'วัย',
  '72',
  'ร้องขอ',
  'ความ',
  'เป็นธรรม',
  'ถูก',
  'เจ้าหน้าที่',
  'รัฐ',
  'ยึด',
  'ที่ดิน',
  'ทำกิน',
  'ที่',
  'มี',
  'เอกสาร',
  'ส.ค.',
  '1',
  'และ',
  'เป็น',
  'ที่ดิน',
  'มรดก',
  'กว่า',
  '80',
  'ไร่',
  'เผย',
  'ทำกิน',
  'มา',
  'ตั้งแต่',
  'รุ่น',
  'พ่อ',
  'ชี้',
  'รัฐ',
  'รังแก',
  'ประชาชน',
  'เตรียม',
  'เดินหน้า',
  'ยื่น',
  'หนังสือ',
  'นายก',
  'ฯ',
  'หาก',
  'ช่วย',
  'ไม่',
  'ได้',
  'จะ',
  'ทำ',
  'ฎีกา',
  'ถวาย',
  'ในหลวง',
  'นายอำเภอ',
  'ฯ',
  'โต้',
  'จนท.',
  'ทำ',
  'ถูกต้อง',
  'ตาม',
  'กฎหมาย',
  'อ้าง',
  'ที่ดิน',
  'เป็น',
  'สมบัติ',
  'หลวง',
  '(',
  '1',
  'ก.ย.',
  ')',
  'นาย',
  'ถวิล',
  'จินดาวงศ์',
  'อายุ',
  '72',
  'ปี',
  'ชาว',
  'ต.',
  'ในเมือง',
  'อ.',
  'เมือง',
  'ชัยภูม

In [22]:
vs.y

array([[[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]]])

In [23]:
vs.readable_y

[['O',
  'O',
  'MEA_B',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'ABB_B',
  'O',
  'O',
  'O',
  'O',
  'O',
  'DTM_B',
  'DTM_I',
  'DTM_I',
  'DTM_B',
  'DTM_I',
  'O',
  'O',
  'O',
  'MEA_B',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'TRM_B',
  'TRM_I',
  'O',
  'O',
  'O',
  'O',
  'O',
  'MEA_B',
  'MEA_I',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'ABB_B',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'DTM_B',
  'DTM_I',
  'O',
  'TTL_B',
  'PER_B',
  'PER_I',
  'O',
  'MEA_B',
  'MEA_I',
  'O',
  'ABB_LOC_B',
  'LOC_I',
  'ABB_LOC_B',
  'LOC_I',
  'LOC_I',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  '

# Train new model without pre-train embedding matrix

In [26]:
# from keras.utils import to_categorical
# y = to_categorical(vs.y)
vs.y.shape

(2, 2000, 39)

In [46]:
# Default embedding_matrix = None
default_model = NamedEntityRecognizer(new_model=True)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 2000, 300)         92374500  
_________________________________________________________________
bidirectional_2 (Bidirection (None, 2000, 600)         1442400   
_________________________________________________________________
dense_16 (Dense)             (None, 2000, 39)          23439     
_________________________________________________________________
crf_2 (CRF)                  (None, 2000, 39)          3159      
Total params: 93,843,498
Trainable params: 93,843,498
Non-trainable params: 0
_________________________________________________________________
bi-lstm-crf


In [51]:
default_model.train(vs.x, vs.y, validation_split=0)
# default_model.train(input_array,y)

checkpoint/13-04-2018-15-37-48_untitled checkpoint/13-04-2018-15-37-48_untitled/tensorboard
new callbacks
Epoch 1/1
2/2 [==============================] - 16s 8s/step - loss: 11.7969 - acc: 0.4307


In [52]:
prediction = default_model.predict(vs.x, decode_tag=True)

In [61]:
vs.readable_y[1]

['O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'DTM_B',
 'DTM_I',
 'DTM_I',
 'DTM_B',
 'DTM_I',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'DTM_B',
 'DTM_I',
 'DTM_I',
 'O',
 'O',
 'O',
 'O',
 'DTM_B',
 'DTM_I',
 'O',
 'ABB_DES_B',
 'PER_B',
 'PER_I',
 'O',
 'O',
 'O',
 'ORG_B',
 'ORG_I',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'LOC_B',
 'LOC_B',
 'LOC_I',
 'LOC_I',
 'LOC_B',
 'LOC_I',
 'LOC_I',
 'LOC_I',
 'ABB_LOC_B',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'ABB_LOC_B',
 'LOC_I',
 'O',
 'O',
 'O',
 'TTL_B',
 'PER_B',
 'PER_I',
 'O',
 'MEA_B',
 'MEA_I',
 'O',
 'O',
 'O',
 'O',
 'ABB_B',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 '

In [58]:
vs.x.shape

(2, 2000)

In [57]:
vs.y.shape

(2, 2000, 39)

In [53]:
prediction.shape

(2, 2000)

In [100]:
prediction = default_model.predict(vs.x)

In [75]:
prediction.shape

(2, 2000)

In [101]:
prediction

array([[[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]]], dtype=float32)

In [80]:
default_model.evaluate(vs.x, vs.y)

f1_macro :  0.09576576576576576
f1_micro :  0.94075
precision :  0.09264607118871726
recall :  0.09937791601866253


/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


OrderedDict([('f1_macro', 0.09576576576576576),
             ('f1_micro', 0.94075),
             ('precision', 0.09264607118871726),
             ('recall', 0.09937791601866253)])

In [158]:
# model = NamedEntityRecognizer()

# Train new model with pre-train embedding matrix

In [141]:
# import pickle
# mock_embedding_matrix = pickle.load(open("/Users/jijy/Documents/YEAR4/SPworkspace/sentiment/dump/embedding_matrix.pickle",'rb'))
from bailarn.word_embedder.word2vec import Word2Vec
w2v_model = Word2Vec()

In [142]:
import json
# word_index = json.load(open('./bailarn/categorization/word_index.json'))
embedding_matrix = utils.get_embedding_matrix(word2vec_model=w2v_model, word_index=word_index)

In [143]:
model = NamedEntityRecognizer(embedding_matrix=embedding_matrix, new_model=True)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_18 (Embedding)     (None, 2000, 300)         142200    
_________________________________________________________________
bidirectional_16 (Bidirectio (None, 2000, 600)         1442400   
_________________________________________________________________
dense_30 (Dense)             (None, 2000, 39)          23439     
_________________________________________________________________
crf_16 (CRF)                 (None, 2000, 39)          3159      
Total params: 1,611,198
Trainable params: 1,611,198
Non-trainable params: 0
_________________________________________________________________
bi-lstm-crf


In [134]:
# len(embedding_matrix)

474

In [135]:
# len(word_index)

473

In [144]:
model.train(vs.x, vs.y)

checkpoint/13-04-2018-16-29-59_untitled checkpoint/13-04-2018-16-29-59_untitled/tensorboard
new callbacks
Epoch 1/1
2/2 [==============================] - 21s 10s/step - loss: 12.1555 - acc: 0.0060


In [145]:
# model.evaluate(vs.x, vs.y)

In [146]:
model.model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_18 (Embedding)     (None, 2000, 300)         142200    
_________________________________________________________________
bidirectional_16 (Bidirectio (None, 2000, 600)         1442400   
_________________________________________________________________
dense_30 (Dense)             (None, 2000, 39)          23439     
_________________________________________________________________
crf_16 (CRF)                 (None, 2000, 39)          3159      
Total params: 1,611,198
Trainable params: 1,611,198
Non-trainable params: 0
_________________________________________________________________


In [150]:
model.save('abc.h5')

# Use pre-trained model

- predict on pantip data

In [3]:
from bailarn.tokenizer import constant as tokenizer_constant
from bailarn.tokenizer.tokenizer import Tokenizer

# Create index for character and tag
char_index = utils.build_tag_index(tokenizer_constant.CHARACTER_LIST, tokenizer_constant.CHAR_START_INDEX)
tag_index = utils.build_tag_index(tokenizer_constant.TAG_LIST, tokenizer_constant.TAG_START_INDEX)

tokenizer_model = Tokenizer(char_index, tag_index)

def tokenize_func(sentence):
    return tokenizer_model.predict(sentence)
tokenize_func("ฉันกินข้าว")

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 60, 5)             380       
_________________________________________________________________
bidirectional_1 (Bidirection (None, 60, 512)           536576    
_________________________________________________________________
dropout_1 (Dropout)          (None, 60, 512)           0         
_________________________________________________________________
bidirectional_2 (Bidirection (None, 60, 512)           1574912   
_________________________________________________________________
dropout_2 (Dropout)          (None, 60, 512)           0         
_________________________________________________________________
bidirectional_3 (Bidirection (None, 60, 256)           656384    
_________________________________________________________________
dropout_3 (Dropout)          (None, 60, 256)           0         
__________

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/models.py:291: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '


['ฉัน', 'กิน', 'ข้าว']

In [7]:
import pickle
word_index = pickle.load(open('./bailarn/ner/word_index.pickle','rb'))
word_index["<PAD>"] = 0

In [8]:
sorted(word_index.items(), key=lambda x:x[1], reverse=False)[-10:]

[('๘๔,๐๐๐', 55699),
 ('๙', 55700),
 ('๙,๙๙๘,๐๐๐', 55701),
 ('๙๐๔', 55702),
 ('๙๖\\\x0b\\', 55703),
 ('\u200e', 55704),
 ('–', 55705),
 ('—', 55706),
 ('…', 55707),
 ('UNK', 55708)]

In [9]:
sorted(word_index.items(), key=lambda x:x[1], reverse=False)[:10]

[('<PAD>', 0),
 ('!', 1),
 ('!!', 2),
 ('!!!', 3),
 ('!?!', 4),
 ('"', 5),
 ('#', 6),
 ('$', 7),
 ('%', 8),
 ('&', 9)]

In [10]:
tag_index = utils.build_tag_index(constant.TAG_LIST, start_index=constant.TAG_START_INDEX)
len(tag_index)

39

In [11]:
tag_index

{'ABB': 33,
 'ABB_B': 31,
 'ABB_DES_B': 25,
 'ABB_DES_I': 26,
 'ABB_I': 32,
 'ABB_LOC_B': 23,
 'ABB_LOC_I': 24,
 'ABB_ORG_B': 21,
 'ABB_ORG_I': 22,
 'ABB_PER_B': 27,
 'ABB_PER_I': 28,
 'ABB_TTL_B': 29,
 'ABB_TTL_I': 30,
 'BRN_B': 7,
 'BRN_I': 8,
 'DDEM': 34,
 'DES_B': 3,
 'DES_I': 4,
 'DTM_B': 1,
 'DTM_I': 2,
 'LOC_B': 15,
 'LOC_I': 16,
 'MEA_B': 11,
 'MEA_I': 12,
 'NAME_B': 35,
 'NUM_B': 13,
 'NUM_I': 14,
 'O': 37,
 'ORG_B': 19,
 'ORG_I': 20,
 'PER_B': 9,
 'PER_I': 10,
 'TRM_B': 17,
 'TRM_I': 18,
 'TTL_B': 5,
 'TTL_I': 6,
 'UNK': 38,
 'X': 0,
 '__': 36}

In [12]:
texts = utils.TextCollection(corpus_directory="./bailarn/sentiment/data", tokenize_function=tokenize_func)

100%|██████████| 6/6 [00:02<00:00,  2.22it/s]


Finish


In [14]:
vs = utils.build_input(text_collection=texts,
                        word_index=word_index,
                        tag_index=tag_index,
                        sequence_length=constant.SEQUENCE_LENGTH, # padding size
                        target='ner', for_train=False)

Start building input...
Start generating x...


100%|██████████| 6/6 [00:00<00:00, 4320.31it/s]


In [15]:
vs.x

array([[50608, 45960, 16115, ...,     0,     0,     0],
       [55708, 55708, 52790, ...,     0,     0,     0],
       [ 7332, 55708,  7332, ...,     0,     0,     0],
       [11596, 30123, 54460, ...,     0,     0,     0],
       [55708,  7340, 55708, ...,     0,     0,     0],
       [21019, 38660, 51694, ...,     0,     0,     0]])

In [1]:
# vs.readable_x

In [20]:
model = NamedEntityRecognizer(tag_index=tag_index)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 2000, 128)         7130752   
_________________________________________________________________
bidirectional_5 (Bidirection (None, 2000, 256)         263168    
_________________________________________________________________
dense_17 (Dense)             (None, 2000, 39)          10023     
_________________________________________________________________
crf_2 (CRF)                  (None, 2000, 39)          3159      
Total params: 7,407,102
Trainable params: 7,407,102
Non-trainable params: 0
_________________________________________________________________
bi-lstm-crf


In [21]:
model.predict(vs.x)

array([['O', 'O', 'O', ..., 'X', 'X', 'X'],
       ['O', 'O', 'O', ..., 'X', 'X', 'X'],
       ['O', 'O', 'O', ..., 'X', 'X', 'X'],
       ['O', 'O', 'O', ..., 'X', 'X', 'X'],
       ['ORG_B', 'ORG_I', 'ORG_I', ..., 'X', 'X', 'X'],
       ['O', 'O', 'O', ..., 'X', 'X', 'X']], dtype='<U9')

In [149]:
# model.evaluate(vs.x,y)

# Load pre-train model (edit the value in constant.py)

In [24]:
loaded_model = NamedEntityRecognizer()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 2000, 128)         7130752   
_________________________________________________________________
bidirectional_1 (Bidirection (None, 2000, 256)         263168    
_________________________________________________________________
dense_15 (Dense)             (None, 2000, 39)          10023     
_________________________________________________________________
crf_1 (CRF)                  (None, 2000, 39)          3159      
Total params: 7,407,102
Trainable params: 7,407,102
Non-trainable params: 0
_________________________________________________________________
bi-lstm-crf


In [40]:
loaded_model.predict(vs.x)

array([['DTM_B', 'DTM_B', 'DTM_I', ..., 'X', 'X', 'X'],
       ['NUM_B', 'NUM_B', 'NUM_B', ..., 'X', 'X', 'X']], dtype='<U9')

In [163]:
loaded_model.predict(vs.x, decode_tag=False)

array([[[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]]], dtype=float32)